### ISSUE TITLE
pkgtoglb错误，unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by A245A** [yuntaowu2000/trails-games-tools#2]
![2%((O7F3U$P9B0XH FRL1MK](https://user-images.githubusercontent.com/49858815/171122565-5d0aa1c7-ff2c-4438-8644-0a07da1a50bf.png)
如图所示，不知道为啥会出这样的错误！
python版本是3.9.13

**Comment by yuntaowu2000** [comment]
这是哪个游戏的哪个文件？

**Comment by A245A** [comment]
> 这是哪个游戏的哪个文件？

PC闪轨4的，位置是data/asset/D3D11_ct/I_BATTLE.pkg

**Comment by yuntaowu2000** [comment]
看起来这个代码没法处理一个文件里有多个dds文件但没有模型的，我看一下怎么修

**Comment by yuntaowu2000** [comment]
最新commit修复
